=== wanderingivan/pollapp-example/src/test/resources/DaoTest.dtd
<!ELEMENT dataset (

	users*,
	polls*,
	options*
	
)>

<!ELEMENT users EMPTY>
<!ATTLIST users
    user_id     CDATA #IMPLIED
	username    CDATA #REQUIRED
	password    CDATA #REQUIRED
	joined      CDATA #REQUIRED
	email       CDATA #REQUIRED
	description CDATA #IMPLIED
>

<!ELEMENT polls EMPTY>
<!ATTLIST polls 
	poll_id   CDATA #IMPLIED
	poll_name CDATA #REQUIRED 
	owner_id  CDATA #REQUIRED
	votes     CDATA #REQUIRED
	created   CDATA #REQUIRED
>

<!ELEMENT options EMPTY>
<!ATTLIST options 
	option_id   CDATA #IMPLIED
	option_name CDATA #REQUIRED
	poll_id     CDATA #REQUIRED
	votes       CDATA #REQUIRED
	added       CDATA #REQUIRED
>

=== wanderingivan/pollapp-example/src/test/resources/DaoTestDataSet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset PUBLIC "//UNKNOWN/" "DaoTest.dtd">
<dataset>
	<users user_id="1" username="username" email="test@email" joined="2017-05-05 00:00:01" password="password" />
	<users user_id="2" username="username2" email="test@email2" joined="2017-05-05 00:00:01" password="password" />
	
	<polls poll_id="4" poll_name="name" owner_id="2" votes="0" created="2017-05-05 00:00:01"/>
	<polls poll_id="5" poll_name="name" owner_id="2" votes="0" created="2017-05-05 00:00:01"/>
	
	<options option_id="1" option_name="opt1" poll_id="5" votes="0"/>
	<options option_id="2" option_name="opt1" poll_id="4" votes="0"/>
	<options option_id="3" option_name="opt2" poll_id="4" votes="0"/>
</dataset>
